apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: alertmanager
        type: alertmanager
        url: http://kube-prometheus-stack-alertmanager:9093
        access: proxy
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: false
