apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- acend-s3-env-config.yaml

helmCharts:
  - name: operator
    releaseName: minio-operator
    namespace: minio-operator
    version: 6.0.4
    valuesFile: values.yaml
    repo: https://operator.min.io/
  - name: tenant
    releaseName: acend-s3-tenant
    namespace: acend-s3
    version: 6.0.4
    valuesFile: values-tenant.yaml
    repo: https://operator.min.io/

patches:
- target:
    kind: Tenant
    name: acend-s3
  patch: |-
    - op: add
      path: /metadata/namespace
      value: acend-s3
- target:
    kind: Ingress
    name: acend-s3
  patch: |-
    - op: add
      path: /metadata/namespace
      value: acend-s3
- target:
    kind: Ingress
    name: acend-s3-console
  patch: |-
    - op: add
      path: /metadata/namespace
      value: acend-s3