apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
  - name: operator
    releaseName: minio-operator
    namespace: minio-operator
    version: 4.5.8
    valuesFile: values.yaml
    repo: https://operator.min.io/


