secrets:
  existingSecret: acend-s3-env-configuration

tenant:
  name: acend-s3
  configuration:
    name: acend-s3-env-configuration

  buckets:
  - name: velero-backup
  - name: loki-chunks
  - name: loki-ruler
  - name: loki-admin

  features:
    domains:
      console: https://s3-console.k8s-prod.acend.ch
      minio:
      - https://s3.k8s-prod.acend.ch

  pools:
    - servers: 1
      storageClassName: hcloud-volumes
      size: 5Gi
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"

  metrics:
    enabled: true

  prometheus:
    disabled: true

  prometheusOperator: true

  log:
    disabled: true

ingress:
  api:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    host: s3.k8s-prod.acend.ch
    tls:
    - hosts:
      - s3.k8s-prod.acend.ch
  console:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    host: s3-console.k8s-prod.acend.ch
    tls:
    - hosts:
      - s3-console.k8s-prod.acend.ch