operator:
  env:
  - name: PROMETHEUS_NAMESPACE
    value: "monitoring"
console:
  ingress:
    enabled: true
    host: minio-console.k8s-prod.acend.ch
    tls:
    - hosts:
      - minio-console.k8s-prod.acend.ch