operator:
  env:
  - name: PROMETHEUS_NAMESPACE
    value: "monitoring"
  # - name: MINIO_PROMETHEUS_URL
  #   value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
console:
  ingress:
    enabled: true
    host: minio-console.k8s-prod.acend.ch
    tls:
    - hosts:
      - minio-console.k8s-prod.acend.ch