apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- hcloud-secret.yaml

helmCharts:
  - name: hcloud-exporter
    releaseName: hcloud-exporter
    namespace: monitoring
    version: 4.2.6
    repo: https://promhippie.github.io/charts
    valuesInLine:
      serviceMonitor:
        enabled: true
      config:
        existingSecret: hcloud-secret

