---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: hetzner-csi
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/hetzner-csi/base
    repoURL: https://github.com/acend/infrastructure.git
    targetRevision: HEAD
