---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-replicator
    repoURL: https://helm.mittwald.de
    targetRevision: v2.7.3
    helm:
      releaseName: kubernetes-replicator
      values: |
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system

