apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 2.6.5
    helm:
      releaseName: kyverno
      values: |
        replicaCount: 3
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

