apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.3
    helm:
      releaseName: sealed-secrets
      values: |
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
