---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github_client
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgB95yWy0NbyEsKQ+L3DzirKirvVLuaMKdxCtDKDZ3opXwTwcuqpDIv997pSPTdMDj8kVAFeihMbUl06JIQoOdFKbFjn0aL3uMO5QX2BL2ABxg8CgQQHuLHGlpZukFTW6gUuWmOBuHsuGvxeauuJ39aBcM7ECDmE47jEmYJu6T8ALVwS++Nn1nzNnNgIddOLCfjAFb4KiwuE5K6MjENiHJakENoONymiuXkwz50Snp4NEi0FqdybxvrlqC1PUaNYArR/JeZCXsyUGLv16nI/kkuQc7oezUbx5uXgM4OlFraGcd7XALVD7oc+se3FFfEBPBeTS9JPZb4Yp2ZvnfniwbyiNB3hu88kGcFUeHUol3HztNosVqY4xLLedXsvGsonfB33MJUOoyyvmdvPwm7F+gxkZZFF//ZwaCgG3+/bjECiiHWvCfsnBRy5E6jjpl5fAK1oSBs9UE3WWP0CnR7G6AFA1rbuhsW55QwL1OIxh7zF4Z2I71LRWdrcw29TPjgIe78WdvLcoScJTCOrLQlgPho4vuOr1nB4+qOPyFuGN35pSMvpC02cOMXh1a5VoaVQ1qlWGg/R1bcPsBrJnLdnhLARvJcUgnjWT9n/g85tvsbZQceLynAP2/Zp50CkvsJ3O3+u4GTroyYep8Ad7/ZwA7VdJiMa9WThee9VR2LeTgyJZ9sU/tdFkYWAC+wWaZLsLW+tnbt8wQKnGCbgDaaLJIk6Gdf5Aw==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgBRwW+xOpRD5CLuEQJK5+uPzKs3+jFx5D2nPv5wFbx5cMtW0GYHXVpeoEHOG4wTraayY8ezB1Ot+uZWkvvRA3Qo9j/GzYnjEwEpPIHyXPBTyXtwZcncV5FFMKGx3FKefzU6uAQRHUkDTG4PyZwbw9cRM5ZC52O+AZgQDpjge+yYyln6jk01qzuxA7tJ9uPV3n4qzPWTUolCMJ7Hi8XTO4+lBCKaA7xHZmQoP4i4Y56pMvvp0Km17eBcoib9yU4VfipdEuJrrIGTpYL0BVYOo+8Yb+rQLM++nDuediPLMYfX8AyxCueqklhwHRqrYRgvK2EPxgNGK5B4O3E0pA4JnXpFFub0A9meg7aUsRwwiTNZRlQc/HukgKvuwAue21haWzwbJAqB+Hmxu7MhBlD+KSx15W5a17iT+vrEogX7xp2Fn18fl33MsXijEY7onpPiMvCZXkMxptFdDlX4Xu6yklXKdK74puKFGbqVG+u72ImDJ+UAJVovhjpTTaH2NJNmIHnzi82Y5vRAjZBzaM2PL5fRbQDsV/9gHJCX/msUVYn+2KxSzpk/jbm7EKh5SatJHw4T5hmR269Y1X2dhasDsReFC6JIutPf1LoU8psr7CM06PPlUsdFGWCAvsMmj7N609S9rmsPj6VkDWnkCaW5lc+c24Vy/FvIWnlD5aT0mG0VVFG6z/TG4FrnRs9Lx1bZvmLhCkdT7ZCxjW4Ogh64XE0gi/OMfgqpZ215fc4G5TgoO5/7nGtiYFGB
  template:
    metadata:
      creationTimestamp: null
      name: github_client
      namespace: monitoring

