apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- slack_secret.yaml
- alertmanagerconfig.yaml
- pushprox_etcd.yaml
- pushprox_kube-controller-manager.yaml
- pushprox_kube-scheduler.yaml
- grafana-dashboards/cilium.yaml
- grafana-dashboards/etcd.yaml
- grafana-dashboards/nginx.yaml
- grafana-dashboards/node-exporter.yaml

helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    version: 45.1.1
    valuesFile: values.yaml
    repo: https://prometheus-community.github.io/helm-charts

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: monitoring
    version: 6.50.6
    valuesFile: values-grafana.yaml
    repo: https://grafana.github.io/helm-charts

