---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushprox-kube-etcd-proxy
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-proxy
    component: "kube-etcd"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushprox-kube-etcd-client
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-client
    component: "kube-etcd"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pushprox-kube-etcd-client
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-client
    component: "kube-etcd"
    pushprox-exporter: "client"
spec:
  selector:
    matchLabels: 
      k8s-app: pushprox-kube-etcd-client
      component: "kube-etcd"
  template:
    metadata:
      labels: 
        k8s-app: pushprox-kube-etcd-client
        component: "kube-etcd"
    spec:
      nodeSelector: 
        node-role.kubernetes.io/master: "true"
      tolerations: 
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: pushprox-kube-etcd-client
      containers:
      - name: pushprox-client
        image: rancher/pushprox-client:v0.1.0-rancher2-client
        command:
          - "pushprox-client"
        args:
        - --fqdn=$(HOST_IP)
        - --proxy-url=$(PROXY_URL)
        - --metrics-addr=$(PORT)
        - --allow-port=2381
        - --use-localhost
        resources:
          requests:
            memory: 10Mi
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PORT
          value: :10010
        - name: PROXY_URL
          value: http://pushprox-kube-etcd-proxy.monitoring.svc:8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: pushprox-kube-etcd-client
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-client
    component: "kube-etcd"
spec:
  ports:
  - name: metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector: 
    k8s-app: pushprox-kube-etcd-client
    component: "kube-etcd"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushprox-kube-etcd-proxy
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-proxy
    component: "kube-etcd"
    pushprox-exporter: "proxy"
spec:
  selector:
    matchLabels: 
      k8s-app: pushprox-kube-etcd-proxy
      component: "kube-etcd"
  template:
    metadata:
      labels: 
        k8s-app: pushprox-kube-etcd-proxy
        component: "kube-etcd"
    spec: 
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector: 
        kubernetes.io/os: linux
      tolerations: 
        - key: "cattle.io/os"
          value: "linux"
          effect: "NoSchedule"
          operator: "Equal"
      serviceAccountName: pushprox-kube-etcd-proxy
      containers:
      - name: pushprox-proxy
        image: rancher/pushprox-proxy:v0.1.0-rancher2-proxy
        command:
          - "pushprox-proxy"
        resources:
          requests:
            memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pushprox-kube-etcd-proxy
  namespace: monitoring
  labels: 
    k8s-app: pushprox-kube-etcd-proxy
    component: "kube-etcd"
spec:
  ports:
  - name: pp-proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector: 
    k8s-app: pushprox-kube-etcd-proxy
    component: "kube-etcd"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushprox-kube-etcd
  namespace: monitoring
spec:
  endpoints: 
    - port: metrics
      proxyUrl: http://pushprox-kube-etcd-proxy.monitoring.svc:8080
  jobLabel: component
  podTargetLabels:
  - component
  - pushprox-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels: 
      k8s-app: pushprox-kube-etcd-client