envFromSecret: github-client
grafana.ini:
  server:
    domain: grafana.k8s.labz.ch
    root_url: https://grafana.k8s.labz.ch
  auth.github:
    enabled: true
    allow_sign_up: true
    client_id: aaaabbbbcccc
    client_secret: ddddeeeeffff
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    allowed_organizations: acend
  auth:
    disable_login_form: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
  - grafana.k8s.labz.ch
  path: /
  tls:
  - hosts:
    - grafana.k8s.labz.ch
    secretName: grafana-general-tls

