global:
  rbac:
    createAggregateClusterRoles: true
kubeProxy:
  enabled: false # kube-proxy less installation
kubeScheduler:
  enabled: false # scraping via pushprox as binded to localhost
kubeControllerManager:
  enabled: false # scraping via pushprox as binded to localhost
kubeEtcd:
  enabled: false # scraping via pushprox as binded to localhost
grafana:
  enabled: false  # used antoher helm chart which is better configurable
prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

