apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kubernetes-replicator
    releaseName: kubernetes-replicator
    namespace: kube-system
    version: 2.10.2
    repo: https://helm.mittwald.de
    valuesInLine:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      replicationEnabled:
        secrets: true
        configMaps: false
        roles: false
        roleBindings: false
        serviceAccounts: false
