apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []


helmCharts:
  - name: kubernetes-replicator
    releaseName: kubernetes-replicator
    namespace: kube-system
    version: v2.7.3
    valuesFile: values.yaml
    repo: https://helm.mittwald.de

