---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: '2.7.3'
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: kube-system
      interval: 1m
  values:
    configuration:
      timeZone: Europe/Zurich
      startTime: 21:00
      endTime: 23:59:59
      rebootDays: [sun,mon,tue,wed,thu,fri,sat]

    
