---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: kube-system
spec:
  encryptedData:
    webhook-url: AgB7syTvKvY4B8ELruaC2J+kXAiPHDQsTOOE7BuKQI2UfYu4wF9oBGdQ0OQ0Y9kL4sGbSTemUHKcRrekUEIMMn70fvBJymYmMzQBGDjM5REqRfR/PSuZFB+tsR7+T3yOOa4ZB3sZxKa++yIBHf/axuk09nAQG2rjPWhY7l38Qab3uyLSNha76wZEGE5kR/5AZJvq3+d6DcEGNH2f9eI/07HKaC0M1fr9Dq+M6GQGtG2rBnKoSks85ZvAVNFBvjjNw07nOoyJbCqIYgzDACbNQnMH3oQXJk7qFUDfzLPfpTBXSPkGHpKZUrOkSwIi+aapw1by1lMSr3KSrrUERMjFt2x5kG9hsCQNTeCo+cc58GrRZf/BcfkOdQlLyG4S3a59uS7XESW3fGkXwYBqEENzDP+qz59ct1EelwM/E0lYEaHxHtaWcTxPxlvjkOjhBhnyr6cW4mL7Ug/v1IsP0cKXnjqY6LbAJim89TrLfE2proRTAcspW+b+XetAYSJluSEOGafcrdSrdJZBN14Wu5ks35sV391qolSKOtPory0OVvJVx/Evpnj8fIdz6rF2t+eo2DgTgeWUUm7wcQz+VpT0rnis0c3wyfaMFS8pxXkK0CgguJDJTbWlwZO/JYJh/cY1ZWmjYuv3DZ/WAGYi7CqH1ETecPEh/F7SHOnRFS6LS8ixoKRGQqS0DVz24V5PMoY37GVI49OTFLfHr1w2dfdC4lA/mKkDng5vYgdR3vU+Ba+Dbj642IS33a80WWsvesOp7gDXM9Gf5NgKkjGmZ29Z0UMxNYjw0D0=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: kube-system