---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: kube-system
spec:
  encryptedData:
    webhook-url: AgA1CeHYApkqvNkMlXAXcYVP8fZJsdYIMW6qqVSS0vo9W8RwWHJNmeWuGg0GMvaV1tr+IQ71jEdL94bxsFUrYfewr6l3D6SsDsum+Hmd/ZleB94EnBrbBUjXK2jrGTkcK9N+zdr1zdoc0dNrirUj75XTOxwdWg5bygoysA2mTBvOUbqVRkXW8yJb2ejEhfADPdPexDRYPOrMzad4CJStqTPSkFEsRrtdqPvElHvC6l/q5IYG7DEyYvUxmnQMjZCxRf4fH6HVxjeg8SqoB1/jKYNZ3Ye3z4l74b+PQMmVcwANq1bEx6K/ut8DB/oLhaIP34ySTn4l+Fslr9/v/K0eTX79Hch8Z63mp5nGDicN5+hXnBJIkzQJyb75HBJUBTVtvfolFwghAiDF0u6fQF5RIff8BdvtNAsulbr5rrQz9cEQNQx2nLPVo30Jfj8aUsBQxlr2hrC+ac4JjBmE5U5RrMuaWHkI8IKz0Klp1sB1lOi165WtKzn5rdJDq6MeC/WW1gYvckM2Q/EY8hP83NEPbhQXA/cwzicYBPQXGaJwMBz0TnU23ZYY1EI68kupSYQ7ZD3YQBAqb+OMugj1LdWsKtTCqwb1rF87pmjfzJX8OXr9VtK1Rn0l5mtW/Wq0r1zw25Z6d+evoOQ7NY8YIUurHQs7rSLoUAZsAEX9SV5FCsvYn8DjTsNibvdk+DvT8r8IqOFqNcTtvI4VlMSdlL0sn+awQZujV1UQ3e6CTi9D7GnSohEv5UOwQw1GXkofeMdeZgAMhHRkUqfv/ufwZq20
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: kube-system