apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-oauth-proxy

resources:
  - namespace.yaml
  - secret.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: github-oauth-proxy
    namespace: github-oauth-proxy
    version: 8.3.1
    repo: https://oauth2-proxy.github.io/manifests
    valuesFile: values.yaml
