---
apiVersion: v1
kind: Namespace
metadata:
  name: github-oauth-proxy
  labels:
    app: github-oauth-proxy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acend-main-wildcard
  namespace: github-oauth-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-local-acend-website
  target:
    name: acend-main-wildcard
    template:
      type: kubernetes.io/tls
  data:
    - remoteRef:
        key: acend-main-wildcard
        property: tls.crt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: tls.crt
    - remoteRef:
        key: acend-main-wildcard
        property: tls.key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: tls.key