config:
  existingSecret: github-oauth-proxy

extraArgs:
  provider: github
  github-org: acend
  github-team: team-stream-1
  email-domain: "*"

ingress:
 enabled: true
 hosts:
   - github-oauth-proxy.acend.ch
 tls:
 - hosts:
   - github-oauth-proxy.acend.ch
   secretName: oauth-tls-secret