config:
  existingSecret: github-oauth-proxy

extraArgs:
  provider: github
  github-org: acend
  github-team: team-stream-1
  email-domain: "*"
  scope: "user:email"
  custom-sign-in-logo: https://raw.githubusercontent.com/acend/.github/main/profile/images/AC-logo-claim-rgb-red.svg
  pass-authorization-header: true
  whitelist-domain: "*.acend.ch,localhost:*"

ingress:
 enabled: true
 hosts:
   - github-oauth-proxy.acend.ch
 tls:
 - hosts:
   - github-oauth-proxy.acend.ch
   secretName: oauth-tls-secret