---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-syetem
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '0.19.4'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: kube-system
      interval: 1m
  install:
    crds: Create
  values: {}
    
