---
kutt:
  admin:
    emails: sebastian@acend.ch
  config:
    disallowAnonymousLinks: true
    disallowRegistration: false
    siteName: acend.ch URL shortener
  domain:
    useFirstIngressHost: true
  mail:
    contactEmail: info@acend.ch
    username: johann@acend.ch
    existingSecret: kutt-smtp-config
    from: noreply@acend.ch
    host: smtp-relay.gmail.com
    port: 587
  jwt:
    existingSecret: kutt-jwt-key

extraEnv: 
- name: DEBUG
  value: "*"

postgresql:
  enabled: false
  

ingress:
  enabled: true
  hosts:
  - host: go.acend.ch
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
      - go.acend.ch
    secretName: kutt-tls-secret

externalPostgresql:
  auth:
    database: kutt
    existingSecret: cluster-kutt-user
    username: kutt
    userPasswordKey: password
  hostname: kutt-rw
