apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterissuer.yaml
- hosttech-secret.yaml



helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.11.0
    valuesFile: values-certmanager.yaml
    repo: https://charts.jetstack.io
  - name: cert-manager-webhook-hosttech
    releaseName: cert-manager-webhook-hosttech
    namespace: cert-manager
    version: 0.3.0
    valuesFile: values-certmanager-webhook-hosttech.yaml
    repo: https://piccobit.github.io/helm-charts

