apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterissuer.yaml


helmCharts:
  - name: kubernetes-replicator
    releaseName: kubernetes-replicator
    namespace: cert-manager
    version: v1.11.0
    valuesFile: values-certmanager.yaml
    repo: https://charts.jetstack.io


