apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- velero-s3-secret.yaml
- schedule.yaml

helmCharts:
  - name: velero
    releaseName: velero
    namespace: velero
    version: 10.1.1
    valuesFile: values.yaml
    includeCRDs: true
    repo: https://vmware-tanzu.github.io/helm-charts
