initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  existingSecret: velero-s3-secret

configuration:
  extraEnvVars:
    - name: AWS_EC2_METADATA_DISABLED
      value: "true"
  backupStorageLocation:
    - name: hcloud
      bucket: acend-s3-storage
      prefix: velero
      provider: velero.io/aws
      default: false
      credentials:
        name: velero-s3-secret
        key: cloud
      config:
        region: nbg1
        s3Url: https://nbg1.your-objectstorage.com
        publicUrl: https://nbg1.your-objectstorage.com
        insecureSkipTLSVerify: true
        s3ForcePathStyle: false
        profile: hcloud
        checksumAlgorithm: ""

snapshotsEnabled: false
deployNodeAgent: false

nodeAgent:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    autodetect: false
  prometheusRule:
    enabled: true
    autodetect: false
    spec:
      - alert: VeleroBackupPartialFailures
        annotations:
          message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
        expr: |-
          velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
        for: 15m
        labels:
          severity: warning
      - alert: VeleroBackupFailures
        annotations:
          message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
        expr: |-
          velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
        for: 15m
        labels:
          severity: warning
