initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  existingSecret: velero-s3-secret

configuration:
  backupStorageLocation:
    - name: default
      bucket: velero-backup
      provider: aws
      default: true
      credentials:
        name: velero-s3-secret
        key: cloud
      config:
        region: minio
        s3Url: https://minio.acend-s3.svc.cluster.local
        s3ForcePathStyle: true
        insecureSkipTLSVerify: true
        publicUrl: https://s3.k8s-prod.acend.ch

snapshotsEnabled: false
deployNodeAgent: false

nodeAgent:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

metrics:
  enabled: true
  serviceMonitor: 
    enabled: true
    autodetect: false
  prometheusRule:
    enabled: true
    autodetect: false
    spec:
    - alert: VeleroBackupPartialFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
      expr: |-
        velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning
    - alert: VeleroBackupFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
      expr: |-
        velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning