apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-secret
  namespace: velero
spec:
  encryptedData:
    hcloud: AgA5Isk13mxL3FJqGMM9JOMt+hWlVTpGbaIFR+gCUcVmu0/v2rQm3Uvknoz91EZNFjfKfYxs/p7UKPGB9skt1Sfc9fF54naR2dRS5pJUAfRWgekToLu3DL0dAe8QkKYaN4ad+F1voE4m1hpFzmOGxvN1KVjXiXYIpdebf/dFipAfdPa/Vvew2F5CYUWsPAxyHbUqNbbZJCMtPVNpcqZenfSvQ6rJ28JHsDildq19SmOrLAFMuy5esa2Ez3QQs3h0JY3TXje2PvMKmzFgiz3WnXARvOwie+bOFQzOJjiO3UJl6wxzoPv1LFmg/FO8xRADRlHknBkS2DfC/+YpM+BPD72KvCuXYqpPcKrZ1aaX3QbmwEQvSkmDnMwlxgWzACXgVKj6EpQDjwwsPMGutort6Toxq/Ci/jATya6a2r5j9wx+egBbzVUUhOF4WN814naDX+PYmhLyGDYXx90Xy4W1ZDEh93NY9TfJdXugRdcC2p5d8En83iFG9Qou0y4n54TOZwWrxIMCNjeS7CUCzvAJRLfOrVIlMxbtB8IR7Ou29FhNsGqB3saOZYeIVxts1lekZ5EenquUsai3RJgROaIXSCsdgoEJo0yOsvwqKE8BfSvZO0/SyLyl/UnwmNZb+rnc0jpCnsx59FOa82jBwehHlTjhhCXTTd19TznF9tmx4ErlcMiPz4K94DLWkdzO9flFtbzUXHJSzG1Wih+8WLm8yyAQnjIGehlDQiO6AIiMTTU2oC2mXXB1hBEm05V2xegERYlp8Wpk2ascy7xCA9F9Fhl+XLW3frlHVX5lc6fvGZqR0cUtmU4XWfJxV1qa8dPIuMo+OoWAgoAYXHbvH45tjZo=
    minio: AgCKLASJ1peQr7bEjoEB/LOPmlD7QCSS07jnrI8Y3tVk0yPdK1xUHWgQ16d1kjW+5QraQfotHSVjcJ+AQtNJpjpDPwe2ea/aV/yxOxXIr8+Xf6b1NbGirXNf+Y+hr3bq6P1b8jmE420jHavakSCtaFSRQ0EhI7TGZDO0BzCVzdP0dEleBRaBrV96wai5ppEVyvVDprgfQOPW16NMAUTlc7vBTQSDcgzFpLYAd+RmogaB5MnwOOrFf10QvaprE5KW6Ie0Ab4lZK5jXM4ulJZfhAT6FnJ6c9MWY+PIQS/XzdHbOChgMhytb7rd2mum7ODab1yizuELxRVm0JEIUAGHWxWHXyBiLJ1b5j6qp1mRSaO8KC5yl08OlUsiZ8GtfmXFrB38TRvJvq7wFpjR2xsgyZf7iYCt+7KxmJ47pWahlLMsmbYAekEkbZQlAIDvmuJr6Sum1nsa0Qi1UgUL0eTvtyTCZ//nYoKM9nDB/MCJFL8U4uxbbjQt/rQXOWmmukRfseBw/UE/bvYvrxxk+l1tnaL6VoA+IIEXwa5gKBUhDqSxQ86d07OOJW42nL9+Yopk0kCt7ZVF/kJG3hUAG4Da/KR19TdaeTSPPZ2vNKHTqeUnScNtoPcC4/mEupk0TJUWR+kMw/Cl+c5rhj3I48vIs00CwZ5riLXia/GACi5vd/VfOMUCLKrRZ6oFT6w+NeXOK4yPB89H6JUQMD8XSl21ghrgH4gXsnzKJ6m0NiBqQH6zRKetfAF5uh+KFLhv8/srciIqqhTHlFc5LLTCzrKfoby0Ogsw0Ngxdz3coIMnSgImLo1whRibdx4mUe27vaWPKrI4yXQ=
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-secret
      namespace: velero
    type: Opaque

