---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgCcUjTdcUz8kJwkwiC4wh6DaIiYVS0R2cMTPZ8XB0XYGoI5y33Ekq01oRow9Im+D+4NxK3/neHROz3EQAHTP6yvk6awa54TOZuSVQTIPQle8/w2+DskSq7CAMaH5/tpgS12+STMSRQIRLdH43XDLtivs8vjOaP5CBGjo1VABVuofuJ95x2xeOY/8kC0VCjUZ/axPw5VO4b2IvNU2pAlU+iWFXj5+4BZiIwXkaOxm0oSHZuRymib+Z+jTgU8lRD+4NIZt8ecOrQt9n+Sz77dkheBE/1XStxxAl0fKjg+dLZwRa5RoSWY/BJTNwGy3cHCoAtiB0hjllh0jM0e+olTmIhCcbt80mTJyrUmf89Q7u5raJBn0nDsGNmo15FMpQr8cEs1fxziI6Pj959yM9XkFSn33j0R1Jp0LmvFL9cwFBWH3mT14nN6+zu82UC1Xzr6lWBQkZlZ7z/nYqR4OI3aeepKCy2b50Nd7zPRritjr42SueB2F31+bnLavQ1xfns7YZ5vq9yfkINJYqS4Gmq9fUlgXNojxqvn3a6//Zy8LYFd3blGvYPsLkwipZF3rMuwHfB4N/NxPPvqyK2CzEo8LdfbqiRxTfG1Z2lpblOJE8wq33htH841VWBf7m4oMZBEliwA0xOXvBBF4aw77GydD3HQ+Re/79N63C9B3txOoX5q7pvNjmvQg5RHscreVdNR+kYdw9n7dUq/8BJUnWNaexm+MSsGxKL30/U10ChblAziNL1U2dY4n1dmgkfXEWz9cB99IHHRaScb+y2KgCszMOfoJ8Q0Ynn5ded0r72TFlWnrosTkq959ha2oYV+u30TeLWKnU4=
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-secret
      namespace: velero