apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgCfE4weqV/Tb6iWUIO1aXemrZeoFFxP1BzALEaOWku/iX6KpzE2NW+x82nlI1Ye2WZ2aP5QNbHkTh4TMJuwmTak7tp+GCnzsFzO6g6e2cQF9mwxcgWBU6U4oHRoj1kB0NqXLyt/J67ffJQzYeqwDROIXYuJ6sDMlnI160n8WPzLUHOSLQOCtBMZHfoSdICDZYdHdtjHSd2QYWMaQpH13pe3TPjwzrbs8NpnlcMCLXUET41B126/Y7ilDFNEIY+OO+WlgCx/tgtjCxZBsFEps9iXioz7VPkUVvU4bGYUFY+zAfohqJvm6F4acndeL51hwc1G8ft1EIRnS+RXzAdDJIDT/Sph11jChdttBn8BOQxpDEA/c3WDBcTmLEYNnEreEnxUyvcLrOHSzikjM/Ba8TuyoaGzKKraIMA3WQDc/5SktYboOeifICtd7TzbekKMJZ/wOxrxIkV7aBNJngnUBAqc//DY2isHTIqC2BvZDULRkr5G/cpOtDimcED9dJ3s2AxhOSPOGJolQ8lX43fXNdxTq337/bGYmX3DanSiXuqnnCa+h3Hgje7IqKvvktCAHwnD2C+TCcPq2nqQLcBQtVwyCyQwW/euCdrPZBxROaahmw7qVXBBpa+/b4hQwf5JjpclU5VepIX2s8M/QMpoJgDGPnLzkcCXQUSQl6wt/bNaRClx5VrCzSTtdYt4ridVukiA2Tdb7pvoK/BXHzQMAHFsyZC2k3JloLjf9f3rPWLI/oNw36FMqzljDw7NpK5Dpvsd+NKCZktI2GKGUMRFS3b4mX6YxrzpvwwZCSn4t+47kUISH8d1K3oTR/Lsm4qvE/pm6wGRRNTnzG/ziq+uMfFE/ENlpspbQF5LBydsRE1GHWrxZ+DbycsVR9Qzvmol76pcoN+icq2cgK6aLWjsHv9sKIzaJz+LwRsrmjQ9PNeSRiJytRrqMw4Ak+MwZMUnHea8gNBxi5oX2cgtXcSLMv56
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-secret
      namespace: velero
    type: Opaque

