apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true
    version: 0.14.4
    valuesFile: values.yaml
    repo: https://charts.external-secrets.io

