---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: acend-website
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: acend-website
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: acend-website
data:
  maxmemory: 64mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: acend-website
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /redis-master-data
            - name: redis-config
              mountPath: /redis-master
          readinessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
        - image: wordpress:6-php8.3-apache
          imagePullPolicy: Always
          name: wordpress
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: WORDPRESS_DEBUG
              value: "1"
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/custom.ini
              subPath: custom.ini
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          emptyDir: {}
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: php-config
          configMap:
            name: wordpress-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  namespace: acend-website
data:
  # yamllint disable rule:line-length
  custom.ini: |
    file_uploads = On
    memory_limit = 512M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: acend-website
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: acend-website
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: acend-website
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:11.5.2
          name: mariadb
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 300
            periodSeconds: 10
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MARIADB_DATABASE
              value: "wordpress"
            - name: MARIADB_USER
              value: "wordpress"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ing
  namespace: acend-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - events.acend.ch
      secretName: acend-main-wildcard
  rules:
    - host: events.acend.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
