---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
  name: acend-website
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
  name: acend-website-test
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
  name: acend-slack-notify 
