---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acend-wildcard
  namespace: acend-website
spec:
  dnsNames:
  - '*.training.acend.ch'
  - '*.training.puzzle.ch'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  secretName: acend-wildcard
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: acend-.*
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acend-test-wildcard
  namespace: acend-website-test
spec:
  dnsNames:
  - '*.test.acend.ch'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  secretName: acend-test-wildcard
