---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
  name: acend-tekton-basics-training-prod
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
  name: acend-tekton-basics-training-test