---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "prod"
  name: acend-hugo-training-template-prod
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "test"
  name: acend-hugo-training-template-test 