---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acend-wildcard
  namespace: acend-website
spec:
  dnsNames:
  - '*.training.acend.ch'
  issuerRef:
    kind: ClusterIssuer
    name: acend-letsencrypt-acme
  secretName: acend-wildcard
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: acend-.*