---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift-operations
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'acend-ocp-uptime-monitoring-prod'
    server: '*'
  sourceRepos:
  - '*'
