---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- acend-wildcard-certificate.yaml
- acend-ted-lasso.yaml
- acend-website-basicauth.yaml
- acend-website-config.yaml
- argocd-appprojects.yaml
- acend-events.yaml
- acend-events-secrets.yaml
- secretstore.yaml
- namespaces/
- plausible/
