---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-local-acend-website
spec:
  provider:
    kubernetes:
      remoteNamespace: acend-website
      auth:
        serviceAccount:
          name: "eso-store"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-local-acend-website-test
spec:
  provider:
    kubernetes:
      remoteNamespace: acend-website-test
      auth:
        serviceAccount:
          name: "eso-store-test"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets