---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-local-acend-website
spec:
  provider:
    kubernetes:
      remoteNamespace: acend-website
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt