controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  config:
    url: "https://argocd.${cluster-domain}"
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - kinds:
        - "ciliumidentities"
        - "ciliumendpoints"
        - "ciliumnodes"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - "argocd.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd.${cluster-domain}"
      secretName: argocd-tls
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - "argocd-grpc.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd-grpc.${cluster-domain}"
      secretName: argocd-grpc-tls
    
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true