global:
  domain: "argocd.${cluster-domain}"

controller:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

configs:
  cm:
    create: true
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 84974c1322a2a09b728d
            clientSecret: $dex.github.clientSecret
            orgs:
            - name: acend

  rbac:
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, applicationsets, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, projects, get, *, allow
      g, acend:team-cluster-admins, role:org-admin
  secret:
    extra:
      dex.github.clientSecret: ${github-app-argocd-clientSecret}

dex:
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
server:
  config:
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - kinds:
        - "CiliumIdentity"
        - "ciliumidentities"
        - "CiliumEndpoint"
        - "ciliumendpoints"
        - "CiliumNode"
        - "ciliumnodes"
  resources:
    requests:
      cpu: 50m
      memory: 120Mi

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hostname: "argocd.${cluster-domain}"
    extraTls:
    - hosts:
      - "argocd.${cluster-domain}"
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hostname: "argocd-grpc.${cluster-domain}"
    extraTls:
    - hosts:
      - "argocd-grpc.${cluster-domain}"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 120Mi

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 80Mi

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 30Mi