controller:
  metrics:
    enabled: true

server:
  config:
    url: "https://argocd.${cluster-domain}"
    resource.exclusions: |
      - kinds:
        - "ciliumidentities"
        - "ciliumendpoints"
        - "ciliumnodes"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - "argocd.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd.${cluster-domain}"
      secretName: cluster-wildcard
  ingressGrpc:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - "argocd-grpc.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd-grpc.${cluster-domain}"
      secretName: cluster-wildcard
    
  metrics:
    enabled: true