controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

configs:
  cm:
    create: true
    url: "https://argocd.${cluster-domain}"

    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 84974c1322a2a09b728d
            clientSecret: $dex.github.clientSecret
            orgs:
            - name: acend

  rbac:
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, exec, create, */*, allow
      p, role:org-admin, projects, get, *, allow
      g, acend:team-cluster-admins, role:org-admin
  secret:
    extra:
      dex.github.clientSecret: ${github-app-argocd-clientSecret}

server:
  config:
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - kinds:
        - "CiliumIdentity"
        - "ciliumidentities"
        - "CiliumEndpoint"
        - "ciliumendpoints"
        - "CiliumNode"
        - "ciliumnodes"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
    - "argocd.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd.${cluster-domain}"
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
    - "argocd-grpc.${cluster-domain}"
    https: true
    tls:
    - hosts:
      - "argocd-grpc.${cluster-domain}"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
