#cloud-config
%{ if length(extra_ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in extra_ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
packages:
- git
- jq
- curl
- open-iscsi
- unattended-upgrades
write_files:
- path: /etc/rancher/rke2/config.yaml
  permissions: "0600"
  owner: root:root
  content: |
    server: https://${lb_address}:9345
    token: ${rke2_cluster_secret}
    cloud-provider-name: external
- path: /opt/rke2/run_rke2.sh
  permissions: "0755"
  owner: root:root
  content: |
    #!/bin/bash
    function one_healthy {
      res=$(jq -r '.load_balancer.targets | .[] | select(.label_selector.selector == "cluster=${clustername},controlplane=true") | .targets | any(.health_status | all(.status == "healthy"))')
      test "$res" = "true"
    }
    function get_lb {
      LB="$(echo ${lb_id} | cut -d \- -f 1)"
      curl -sSL -H "Authorization: Bearer ${api_token}" "https://api.hetzner.cloud/v1/load_balancers/$LB"
    }
    while true; do
      get_lb | one_healthy
      if [ "$?" == 0 ]; then
        break
      fi
    echo "controlplane is not ready yet"
    sleep 10
    done
    curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh --output install.sh
    chmod u+x install.sh
    NODE_IP=$(curl -s http://169.254.169.254/hetzner/v1/metadata/private-networks | grep "ip:" | cut -f 3 -d" ")
    echo "node-ip: $NODE_IP" >> /etc/rancher/rke2/config.yaml
    INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION=${rke2_version} ./install.sh
    systemctl enable rke2-agent
    systemctl start rke2-agent
    sleep 20
    for bin in $(readlink -f /var/lib/rancher/rke2/bin/*); do
      ln -sf $bin /usr/local/bin/$(basename $bin)
    done
runcmd:
- /opt/rke2/run_rke2.sh
