---
secret:
  create: true

gitRepository:
  spec:
    url: ${giturl}
    ref: 
      branch: main
    ignore: |
      # exclude all
      /*
      # include deploy dir
      !/deploy/

kustomization:
  spec:
    path: "./deploy/bootstrap"