apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: cluster-autoscaler
    releaseName: cluster-autoscaler
    namespace: kube-system
    version: 9.47.0
    valuesFile: values.yaml
    repo: https://kubernetes.github.io/autoscaler

