---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-replicator
      version: 'v2.7.3'
      sourceRef:
        kind: HelmRepository
        name: kubernetes-replicator
        namespace: kube-system
      interval: 1m
  values:
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    nodeSelector:
      node-role.kubernetes.io/control-plane: true
    
