apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml


helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: 4.4.2
    valuesFile: values.yaml
    repo: https://kubernetes.github.io/ingress-nginx

