apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - namespace.yaml
  - wildcard-certificate.yaml

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: 4.10.1
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: values.yaml
