apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: descheduler
    releaseName: descheduler
    namespace: kube-system
    includeCRDs: true
    version: 0.30.1
    valuesFile: values.yaml
    repo: https://kubernetes-sigs.github.io/descheduler/

