apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: descheduler
    releaseName: descheduler
    namespace: kube-system
    includeCRDs: true
    version: 0.33.0
    valuesFile: values.yaml
    repo: https://kubernetes-sigs.github.io/descheduler/

patches:
- target:
    kind: ClusterRole
  patch: |
    - op: add
      path: /rules/-
      value:
        verbs: ["get", "watch", "list"]
        apiGroups: ["policy"]
        resources: ["poddisruptionbudgets"]