deschedulerPolicy:
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            evictLocalStoragePods: true
        - name: RemoveDuplicates
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: HighNodeUtilization
          args:
            thresholds:
              pods:   90
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - HighNodeUtilization
        deschedule:
          enabled:
            - RemovePodsViolatingInterPodAntiAffinity
serviceMonitor:
  enabled: true

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
