---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 'v2.5.3'
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 1m
  values:
    replicaCount: 3
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"

    
