apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-secret-generator

resources:
  - namespace.yaml

helmCharts:
  - name: kubernetes-secret-generator
    releaseName: kubernetes-secret-generator
    namespace: kubernetes-secret-generator
    version: 3.4.0
    repo: https://helm.mittwald.de
    includeCRDs: true
