---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: ingress-nginx
#   namespace: ingress-nginx
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: ingress-nginx
#       version: '4.4.2'
#       sourceRef:
#         kind: HelmRepository
#         name: ingress-nginx
#         namespace: ingress-nginx
#       interval: 1m
