---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m0s
  chart: ingress-nginx
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: ingress-nginx
  version: '4.4.2'
  valuesFiles:
    - values.yaml