apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: goldpinger
    releaseName: goldpinger
    namespace: goldpinger
    version: 5.6.0
    repo: https://okgolove.github.io/helm-charts/
    valuesInLine:
      service:
        type: ClusterIP
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
