apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy-system

resources:
  - namespace.yaml
  - grafana-dashboard.yaml

helmCharts:
  - name: trivy-operator
    releaseName: trivy-operator
    namespace: trivy-system
    version: 0.11.1
    repo: https://aquasecurity.github.io/helm-charts
    valuesFile: values.yaml
    includeCRDs: true
