apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    version: 2.14.1
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesInLine:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      metrics:
        serviceMonitor:
          enabled: true
        dashboards:
          create: true
          labels:
            grafana_dashboard: "1"
          namespace: monitoring
