apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    version: 2.7.3
    valuesFile: values.yaml
    repo: https://bitnami-labs.github.io/sealed-secrets

