---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "prod"
  name: acend-kubernetes-basics-training-prod
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "test"
  name: acend-kubernetes-basics-training-test
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acend-wildcard
  namespace: acend-kubernetes-basics-training-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-local-acend-website
  target:
    name: acend-wildcard
    template:
      type: kubernetes.io/tls
  data:
    - remoteRef:
        key: acend-wildcard
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        key: acend-wildcard
        property: tls.key
      secretKey: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acend-wildcard
  namespace: acend-kubernetes-basics-training-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-local-acend-website
  target:
    name: acend-wildcard
    template:
      type: kubernetes.io/tls
  data:
    - remoteRef:
        key: acend-wildcard
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        key: acend-wildcard
        property: tls.key
      secretKey: tls.key