---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "prod"
  name: acend-ch-open-workshop-tage-training-prod
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    ci-bot: "true"
    env: "test"
  name: acend-ch-open-workshop-tage-training-test