apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail

resources:
- namespace.yaml

helmCharts:
  - name: promtail
    releaseName: promtail
    namespace: promtail
    version: 6.11.3
    valuesFile: values.yaml
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts

