apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail

resources:
- namespace.yaml

helmCharts:
  - name: promtail
    releaseName: promtail
    namespace: promtail
    version: 6.15.3
    valuesFile: values-controlplane.yaml
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
  - name: promtail
    releaseName: promtail-worker
    namespace: promtail
    version: 6.15.3
    valuesFile: values-worker.yaml
    repo: https://grafana.github.io/helm-charts
