serviceMonitor:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

config:
  clients:
    - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
  snippets:
    extraScrapeConfigs: |
      - job_name: k8saudit
        static_configs:
        - targets:
            - localhost
          labels:
            job: k8saudit
            __path__: /var/lib/rancher/rke2/server/logs/audit.log
resources:
  requests:
    cpu: 30m
    memory: 80Mi

extraVolumes:
- name: k8saudit
  hostPath:
    path: /var/lib/rancher/rke2/server/logs/audit.log
    type: FileOrCreate

extraVolumeMounts:
- name: k8saudit
  mountPath: /var/lib/rancher/rke2/server/logs/audit.log
  readOnly: true