apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - namespace.yaml


helmCharts:
  - name: cloudnative-pg
    releaseName: cnpg
    namespace: cnpg-system
    version: "0.21.1"
    repo: https://cloudnative-pg.github.io/charts
    valuesFile: values.yaml