---
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
monitoring:
  podMonitorEnabled: true