# this will deploy the push-secrets helm chart from the k8s-cluster setup for each training cluster
# the helm chart will deploy the PushSecret objects which then will sync secrets from acend cluster to the trainee cluster
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-bootstrap
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          flavor: k8s
          type: training
  template:
    metadata:
      name: 'secrets-cluster-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/acend/terraform-k8s-cluster-lab
        targetRevision: HEAD
        path: 'charts/push-secrets'
        helm:
          releaseName: 'secrets-cluster-{{name}}'
          values: |
            cluster: {{name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "argocd"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 20
          backoff:
            duration: 10s
            factor: 2
            maxDuration: "10m"