apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: kubernetes-event-exporter
    releaseName: kubernetes-event-exporter
    namespace: kubernetes-event-exporter
    version: 2.5.1
    repo: https://bitnami-labs.github.io/kubernetes-event-exporter
    valuesInLine:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
