apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: kubernetes-event-exporter
    releaseName: kubernetes-event-exporter
    namespace: kubernetes-event-exporter
    version: 3.0.1
    repo: https://charts.bitnami.com/bitnami
    valuesInLine:
      config:
        logLevel: info
        logFormat: json
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
