---
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: cluster-admin
rbacBindings:
  - name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: sebastian
        namespace: rbac-manager
      - kind: ServiceAccount
        name: daniel
        namespace: rbac-manager
      - kind: ServiceAccount
        name: thomas
        namespace: rbac-managerpr-43-prometheus-basics-puzzle-84c6986b4c-d55q9
      - kind: ServiceAccount
        name: benj
        namespace: rbac-manager
      - kind: ServiceAccount
        name: raffael
        namespace: rbac-manager
      - kind: ServiceAccount
        name: cschlatter
        namespace: rbac-manager
    clusterRoleBindings:
      - clusterRole: cluster-admin

---
apiVersion: v1
kind: Secret
metadata:
  name: sebastian
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: sebastian
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Secret
metadata:
  name: daniel
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: daniel
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: thomas
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: thomas
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: benj
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: benj
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: raffael
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: raffael
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: cschlatter
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: cschlatter
type: kubernetes.io/service-account-token