---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-store
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: eso-store
rbacBindings:
  - name: eso-store
    subjects:
      - kind: ServiceAccount
        name: eso-store
        namespace: external-secrets
    roleBindings:
      - clusterRole: eso-store
        namespace: external-secrets