---
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: ci-bot
rbacBindings:
  - name: ci-bot
    subjects:
      - kind: ServiceAccount
        name: ci-bot
        namespace: rbac-manager
    roleBindings:
      - clusterRole: edit
        namespaceSelector:
          matchLabels:
            ci-bot: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-bot
  namespace: rbac-manager
  annotations:
    kubernetes.io/service-account.name: ci-bot
type: kubernetes.io/service-account-token