apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml


helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    version: v2.5.3
    valuesFile: values.yaml
    repo: https://kyverno.github.io/kyverno/

