apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

resources:
  - "namespace.yaml"
#  - policy-acend-ns-label.yaml

helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    version: 3.3.1
    repo: https://kyverno.github.io/kyverno/
    valuesInLine:
      kyverno.pdb.apiVersion: "policy/v1"
      reportsController:
        podAnnotations:
          "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
      admissionController:
        replicaCount: 1
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        serviceMonitor:
          enabled: true