apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    version: 2.7.0
    repo: https://kyverno.github.io/kyverno/
    valuesInLine:
      templating:
        enabled: true
      kyverno:
        namespace: kyverno
      replicaCount: 3
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      metrics:
        serviceMonitor:
          enabled: true
