apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml


# helmCharts:
#   - name: loki
#     releaseName: loki
#     namespace: loki
#     version: 4.6.1
#     valuesFile: values.yaml
#     repo: https://grafana.github.io/helm-charts
