apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-secret
  namespace: loki
spec:
  encryptedData:
    S3_ACCESS_KEY: AgBth0mU/LY2igNEz9nm8M9h+OO1YFFy2/ZIMU5EArrjh6DDLiRbmBy6OozTmYl8bhg+PKdxhK1t27c2u2gQHDpE0tyLaJCeDxpixr4oUQOt78AFfaTrRzRVl6c8Aj/vpwLeN+jVMLkzEoDTEffW+7+iwQEWE2kjC+TZpvRBQx47we8g6DhroJQIG8HrR7DyYqluUwovnl9mFFJAF1bRP+JOHNdUasvixsLxxWYJBnBYtGIEdR4W6yM7XLpt6+Q8p0Ymj0SPR9Isf2HTZx7oaA0bxffuFNBhzFrzN1q1PWQyvUeWBDUr8Tiqu1KrRL776zXmfpdo1YXNBN1NTB8grzua//UFiOBboRw/LZx4d4BjgvACcvUzKJ2GuO7AWZ+NpKGew6uTPVuk1L4xMv0I+bLvKh2QD62Ed2gAQHwFtFwGwKD3TTtIwWLkoggc8vvx0GJcR5/R3WCGiAEJyhPpgDT1Iy/fLD9gIwShzDR54gWwuUdwnifHkbYItRxj7bd/svxN1BTqubUgvXpKONeMGqUNNOq6XiRyi0RSTHmMVHIWYI3J/6ddBoUiodtSLwyqoEtP531ajXlW0AMVXWDGITszS8nvUN6awVXQG8jZAGf8O46HaR7gWe7IM4DV7g3UMkxKGsXqasaSbC50fMAVk5SPWUT721BG9mWnFbKhnknOPlGVwLaQzCERgZnfxAstlATYyLzYVjzxmcWkLbvviUyA
    S3_SECRET_KEY: AgC4Dy8k+GkLi9Et6ya+xjAFwni9kpzgafQQ2jCje1maxIPFn/spV9EY5mxI3UFlx8wFOR432GYoOTluJJUPjbFa9vjQqXeRWVxYaOeAWnRyqmghtHB9lLdQZkTzV0AhZmnXP3HmaF55DmegHcgXRbtsCWU5pK1huw9LcQXneHz3wiyslSzi53r1DWJqOTIJmzRURVeulFauHY85aHNIwpkwu2L2+7ZGO0UVCPXfeYK+tL6sd6jumXHmn5fDkIC8IH6DpiJ30YBHUOkM4ep6hVetX8SBlDcu7FMcbRrmFXWwFrokerOCckCktudrW4LDjGePVKyXhfkrXj3C4bFIHReZvCOgIDsDsOsudViFzuYxLEU9PNDECR/RHkOj3RSk2H5eq3fU1xeOhGWkygx4PG1vtx0C/QX/WKSkzLbv6L2sund/VN0BGxQ36KdWPN5eYsedKhfVvXJiJSNvsxKvk3xidHASQvaipRkAL9ihdfdDaYxNehVJOgDg1tRDGw+iETGoZIwHIloQ1RgJ992RN7ivqMquZ3+OjIqGSD5TRZmZszlbtWAtbinoiqPPihr/kgnQfnWL047GHcBUk7sqIjhmVR3uGQnRDk1MjcX6rObazW6N1XZAM0VqRlMJaYjsGKOLM5CFXcKxnlj1ZiEa8tJFWA88wH+mxIm9T3TXrj6zu/bnWH2KJ1RCs3dQfThrSo3EjCVMgV1+bY/G2bcQOWRhPrmu2GMuaNCnhMkkOdzu1w==
  template:
    metadata:
      creationTimestamp: null
      name: loki-s3-secret
      namespace: loki

