apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
spec:
  rules:
  - host: plausible.acend.ch
    http:
      paths:
      - backend:
          service:
            name: plausible
            port:
              number: 8000
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - plausible.acend.ch
    secretName: acend-main-wildcard
