apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

resources:
- namespace.yaml
- loki-s3-secret.yaml

helmCharts:
  - name: loki
    releaseName: loki
    namespace: loki
    version: 4.9.0
    valuesFile: values.yaml
    #includeCRDs: true
    repo: https://grafana.github.io/helm-charts
