global:
  dnsService: rke2-coredns-rke2-coredns

loki:
  auth_enabled: false

  schemaConfig:
    configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        period: 24h
  
  structuredConfig:
    limits_config:
      retention_period: 360h #15 days

  compactor:
    retention_enabled: true
    delete_request_store: s3

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: minio.acend-s3.svc.cluster.local
      insecure_skip_verify: true
      secretAccessKey: ${S3_SECRET_KEY}
      accessKeyId: ${S3_ACCESS_KEY}
      s3ForcePathStyle: true
      http_config:
        insecure_skip_verify: true

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring
  lokiCanary:
    enabled: false
  serviceMonitor:
    enabled: true

gateway:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"

test:
  enabled: false

memberlist:
  service:
    publishNotReadyAddresses: true

write:
  replicas: 1
  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 5Gi
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

tableManager:
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret

read:
  replicas: 1
  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 5Gi
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
  extraArgs:
    - -config.expand-env
  resources:
    requests:
      cpu: 10m
      memory: 70Mi
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

backend:
  replicas: 1
  podAnnotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
  persistence:
    enableStatefulSetAutoDeletePVC: false
  extraArgs:
    - -config.expand-env
  resources:
    requests:
      cpu: 10m
      memory: 130Mi
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
