loki:
  structuredConfig:
    limits_config:
      retention_period: 744h #31 days

  compactor:
    retention_enabled: true

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: minio.acend-s3.svc.cluster.local
      secretAccessKey: ${S3_SECRET_KEY}
      accessKeyId: ${S3_ACCESS_KEY}
      insecure: true # inside cluster, self signed
      s3ForcePathStyle: true

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring

test:
  enabled: false

write:
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret

tableManager:
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret

read:
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret

backend:
  extraArgs:
    - -config.expand-env
  extraEnvFrom:
  - secretRef:
      name: loki-s3-secret