---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '44.3.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  values:
    global:
      rbac:
        createAggregateClusterRoles: true
    alertmanager:
      config:
        receivers: 
        - name: 'slack-notifications'
          slack_configs:
          - channel: '#ops'
            send_resolved: true
            apiURL:
              key: 'webhook-url'
              name: 'slack-webhook-url'
    kubeProxy:
      enabled: false # kube-proxy less installation
    prometheus:
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
           spec:
             accessModes: ["ReadWriteOnce"]
             resources:
               requests:
                 storage: 50Gi

      