apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgDGYPDnPCMO4oe1bFYNyIzviGIlgRwU/zBXkSZfEW/RgWlujdwrwD6zDIn98oarTomHRy3YQKrzMyultMzfX2PNThLoyiKmVcTEB7t3qKjWKy31wj19YX52Erh/tyIEfLxjdCxgLocHXU/wLbWxb9CMrdz5aetBncT+R0LdWbApUPjCw2fh+aXyNX/R8Xld/+im2wEIcJ1onkFG1LuWx54VbdOxUojVZ61goYO3JjhbAw/CGbKgw3Y1ZvXYHx8jSLAePU7yNHIJmec3ufXt5Zww2Hyxrlv2eSTmupVqGjMDrechNxHT2yfZRHmTVckxEndJ6jTwj+FZdlRkS8b2Jf7isAv4oXaWEL/sgGS5+Ki4jt2fD1rUxKiTUuny7KBoMmR4maN/AnZqbbOxvlhG9VxPflfeLCHWEOoFBH3FTEyozuxw78UoL3dFMYNxlsw9ovwQgsDfD0t/0pBGrmjFDOIsLALMRr7DFRj7YRBrhc7/PUyaClGRGM1p9+HJtdLWA8qgijWktTL9B1QRPlND2mMos5oLrJBRzRjIcPSVOpVPi9wF/HkeJ/Ude62HHnbYAn8gH3RoChkFsQAuCShfCoNR+YFVuj+KDxioFJCg/DiUQT7YQDu8T8X1oXR72xHyaf75hYKGZWI2TISWf7rSoGmd3tW5xCDfVDn1KAbYAxxWTvkUne6ZFgi2nJQiqWe5z1v3Zhz8XWN/ABxD8m4UMLHhidnswxx1WDu4FqOa2V8g8QC4L4ES2niMnV24HbCBIjajnmoxZsXYv45c4zn+oDNGz9iZElActrPYwmzXg0PyXgU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque